spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee-task-management
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: tiriworktracknoreply@gmail.com
    password: "icah dasi qtfa fszw"
    test-connection: true
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
            auth: true
    transport:
      protocol: smtp

  #

  gateway:
    url: http://196.43.100.53:8901/teleoss/sendsms.jsp

  sms:
    username: Te
    password: TestAcc
    senderId: Test Account
    accountusagetypeid: 1
    unicode: 0
    isallowduplicatemobile: yes