server:
  port: 7203

spring:
  application:
    name: task-manager-dev
  datasource:
    url: jdbc:sqlserver://192.168.10.187;instance=;DatabaseName=task_manager_app;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: "%$Afro123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.office365.com
    port: 587
    username: noreply@afrosoft.co.zw
    password: "%$Afro123"
    test-connection: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true
    transport:
      protocol: smtp

#

gateway:
  url: http://196.43.100.53:8901/teleoss/sendsms.jsp

sms:
  username: Te
  password: TestAcc
  senderId: Test Account
  accountusagetypeid: 1
  unicode: 0
  isallowduplicatemobile: yes
#
#  config:
#    import: configserver:
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#     defaultZone: http://192.168.10.99:7201/eureka/